language: python

python:
  - "3.5"
  - "3.4"

matrix:
  include:
    - python: "3.5"
      install: pip install flake8
      script: flake8 twitch_slinxbot

install:
  - pip install -r requirements.txt